import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { normalizeSiteUrl, SITE_URL } from '../build/seo';

const deployment = normalizeSiteUrl(process.argv[2] ?? 'http://127.0.0.1:4174/');
const canonical = normalizeSiteUrl(process.env.SITE_URL ?? SITE_URL);
const get = (path: string) => fetch(new URL(path, deployment), { signal: AbortSignal.timeout(15_000) });
const html = await get('');
assert.equal(html.status, 200);
assert.ok(!html.headers.get('cache-control')?.includes('immutable'));
const home = new JSDOM(await html.text()).window.document;
assert.equal(home.querySelectorAll('title').length, 1);
assert.equal(home.querySelector('link[rel=canonical]')?.getAttribute('href'), canonical);
assert.equal(home.querySelector('meta[name=robots]')?.getAttribute('content'), 'index, follow, max-image-preview:large');
assert.ok(home.querySelector('h1')?.textContent?.includes('焦散透镜'));
assert.equal(home.querySelector('meta[property="og:image"]')?.getAttribute('content'), `${canonical}social-preview.png`);
const graph = JSON.parse(home.querySelector('script[type="application/ld+json"]')!.textContent!)['@graph'];
assert.ok(graph.some((item: { '@type': string }) => item['@type'] === 'WebApplication'));

const optics = await get('optics.html');
assert.equal(optics.status, 200);
const article = new JSDOM(await optics.text()).window.document;
assert.equal(article.querySelector('link[rel=canonical]')?.getAttribute('href'), `${canonical}optics.html`);
assert.ok(article.querySelector('#limits')?.textContent?.includes('实物验证'));
const robots = await get('robots.txt');
assert.equal(robots.status, 200);
assert.match(robots.headers.get('content-type') ?? '', /text\/plain/);
assert.ok((await robots.text()).includes(`Sitemap: ${canonical}sitemap.xml`));
const sitemap = await get('sitemap.xml');
assert.equal(sitemap.status, 200);
assert.match(sitemap.headers.get('content-type') ?? '', /xml/);
const sitemapDocument = new JSDOM(await sitemap.text(), { contentType: 'application/xml' }).window.document;
assert.deepEqual(Array.from(sitemapDocument.querySelectorAll('loc')).map(element => element.textContent), [canonical, `${canonical}optics.html`]);
const llms = await get('llms.txt');
assert.equal(llms.status, 200);
assert.match(llms.headers.get('content-type') ?? '', /text\/plain/);
assert.ok((await llms.text()).includes(`${canonical}optics.html`));

const image = await get('social-preview.png');
assert.equal(image.status, 200);
const png = Buffer.from(await image.arrayBuffer());
assert.equal(png.subarray(1, 4).toString(), 'PNG');
assert.equal(png.readUInt32BE(16), 1200);
assert.equal(png.readUInt32BE(20), 630);
assert.ok(!image.headers.get('cache-control')?.includes('immutable'));
const scriptPath = home.querySelector('script[type=module][src]')!.getAttribute('src')!;
const script = await fetch(new URL(scriptPath, deployment));
assert.equal(script.status, 200);
assert.ok(script.headers.get('cache-control')?.includes('immutable'));
assert.equal((await get('this-page-does-not-exist')).status, 404);
assert.equal((await get('assets/missing.js')).status, 404);
console.log('Production metadata, discovery resources, image dimensions, caching and 404 responses verified.');
