name: Test Docker Build

on:
  workflow_dispatch:  # 手动触发
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - '.github/workflows/docker-*.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test docker-compose
        run: |
          docker-compose config
          docker-compose build --no-cache

      - name: Run container test
        run: |
          docker-compose up -d
          sleep 10
          curl -f http://localhost:3000/ || exit 1
          docker-compose down